from flask import Flask, request, jsonify, send_from_directory
from werkzeug.utils import secure_filename

import warnings
import pandas as pd
import json
import os

import matplotlib
matplotlib.use('Agg')

from flask_cors import CORS
import predict as predict_module

warnings.filterwarnings("ignore")

APP_ROOT = os.path.dirname(os.path.abspath(__file__))
PORT = int(os.environ.get('PORT', 5000))

# The Angular production build (npm run build) outputs to ../dist/svc/browser.
# Flask serves those static files directly, so frontend and API share one host/port.
FRONTEND_DIST = os.environ.get(
    'FRONTEND_DIST',
    os.path.join(APP_ROOT, '..', 'dist', 'svc', 'browser')
)

app = Flask(__name__, static_folder=None)

# Only needed when running the Angular dev server (ng serve) separately from
# this API during local development; in production both are served from the
# same origin so CORS doesn't come into play.
allowed_origins = os.environ.get('FRONTEND_URL', 'http://localhost:4200').split(',')
CORS(app, origins=allowed_origins)

data = {}
predict = {}

UPLOAD_FILE_PATH = os.path.join(APP_ROOT, 'uploaded_data.csv')

# login
@app.route('/validate', methods=['POST'])
def validate():
    username_password = request.json
    username = str(username_password['name'])
    password = str(username_password['pass'])
    with open(os.path.join(APP_ROOT, 'user.json')) as f:
        user = json.load(f)
    for item in user:
        if item["name"] == username and item["pass"] == password:
            return {'res': 'welcome'}
    return {'res': 'fail'}

# upload dataset
@app.route('/upload_file', methods=['POST'])
def upload_file():
    f = request.files['file']
    if f:
        filename = secure_filename(f.filename)
        f.save(UPLOAD_FILE_PATH)
        df = pd.read_csv(UPLOAD_FILE_PATH, encoding='latin-1')
        data[filename] = df.to_dict()
        return jsonify({'file': data})
    return jsonify({'file': data})

# get the forecast chart data (observed + forecasted sales by date) plus error metrics
@app.route('/get_file', methods=['GET'])
def get_file():
    return jsonify({'file': data.get('chart', {}), 'error': data.get('error', {})})

# upload no of months to predict
@app.route('/post_input', methods=['POST'])
def post_input():
    di = request.json
    predict['no.of.months'] = di
    return predict

# upload error
@app.route('/post_error', methods=['POST'])
def post_error():
    data['error'] = request.json
    return data['error']

# get error
@app.route('/get_error', methods=['GET'])
def get_error():
    return data['error']

# get no of months to predict
@app.route('/get_input', methods=['GET'])
def get_input():
    return predict['no.of.months']

@app.route('/prediction', methods=['GET'])
def prediction():
    if 'no.of.months' not in predict:
        return jsonify({'error': 'No forecast months set. Call /post_input first.'}), 400

    error = {'MAE': 106.37330517990762, 'MSE': 16626.014678047788, 'RMSE': 128.94190427494,
              'MODEL': 'SARIMAX(2,0,2)(1,1,1)[12]', 'MAPE': 16.05012069}
    data['error'] = error

    n = int(predict['no.of.months']['n'])
    data['chart'] = predict_module.run_prediction(n)

    return jsonify({'file': data})

# forecast plot generated by predict.py, served to the frontend
@app.route('/plot_forecast.png', methods=['GET'])
def get_forecast_plot():
    return send_from_directory(APP_ROOT, 'plot_forecast.png')

# Serve the Angular app. Real static files (js/css/images) are served as-is;
# any other path falls back to index.html so Angular's client-side router
# handles it (e.g. /dashboard, /view).
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve_frontend(path):
    full_path = os.path.join(FRONTEND_DIST, path)
    if path and os.path.isfile(full_path):
        return send_from_directory(FRONTEND_DIST, path)
    return send_from_directory(FRONTEND_DIST, 'index.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=PORT)
